# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Vivado/Project/Multi_protocol/fpga/constraints/ac820_rgbtft.xdc

# XDC: D:/Vivado/Project/Multi_protocol/fpga/constraints/top.xdc

# Block Designs: bd/multi_protocol_bd/multi_protocol_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multi_protocol_bd || ORIG_REF_NAME==multi_protocol_bd} -quiet] -quiet

# IP: bd/multi_protocol_bd/ip/multi_protocol_bd_processing_system7_0_0/multi_protocol_bd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multi_protocol_bd_processing_system7_0_0 || ORIG_REF_NAME==multi_protocol_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/multi_protocol_bd/ip/multi_protocol_bd_xbar_0/multi_protocol_bd_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multi_protocol_bd_xbar_0 || ORIG_REF_NAME==multi_protocol_bd_xbar_0} -quiet] -quiet

# IP: bd/multi_protocol_bd/ip/multi_protocol_bd_axi_interconnect_0_0/multi_protocol_bd_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multi_protocol_bd_axi_interconnect_0_0 || ORIG_REF_NAME==multi_protocol_bd_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/multi_protocol_bd/ip/multi_protocol_bd_axi_protocol_converter_0_0/multi_protocol_bd_axi_protocol_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multi_protocol_bd_axi_protocol_converter_0_0 || ORIG_REF_NAME==multi_protocol_bd_axi_protocol_converter_0_0} -quiet] -quiet

# IP: bd/multi_protocol_bd/ip/multi_protocol_bd_proc_sys_reset_0_0/multi_protocol_bd_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multi_protocol_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==multi_protocol_bd_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/multi_protocol_bd/ip/multi_protocol_bd_multi_protocol_core_0_0/multi_protocol_bd_multi_protocol_core_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multi_protocol_bd_multi_protocol_core_0_0 || ORIG_REF_NAME==multi_protocol_bd_multi_protocol_core_0_0} -quiet] -quiet

# IP: bd/multi_protocol_bd/ip/multi_protocol_bd_xlconstant_evt_valid_0/multi_protocol_bd_xlconstant_evt_valid_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multi_protocol_bd_xlconstant_evt_valid_0 || ORIG_REF_NAME==multi_protocol_bd_xlconstant_evt_valid_0} -quiet] -quiet

# IP: bd/multi_protocol_bd/ip/multi_protocol_bd_xlconstant_evt_trigger_0/multi_protocol_bd_xlconstant_evt_trigger_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multi_protocol_bd_xlconstant_evt_trigger_0 || ORIG_REF_NAME==multi_protocol_bd_xlconstant_evt_trigger_0} -quiet] -quiet

# IP: bd/multi_protocol_bd/ip/multi_protocol_bd_xlconstant_evt_data_0/multi_protocol_bd_xlconstant_evt_data_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multi_protocol_bd_xlconstant_evt_data_0 || ORIG_REF_NAME==multi_protocol_bd_xlconstant_evt_data_0} -quiet] -quiet

# IP: bd/multi_protocol_bd/ip/multi_protocol_bd_xlconstant_evt_dropped_0/multi_protocol_bd_xlconstant_evt_dropped_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multi_protocol_bd_xlconstant_evt_dropped_0 || ORIG_REF_NAME==multi_protocol_bd_xlconstant_evt_dropped_0} -quiet] -quiet

# IP: bd/multi_protocol_bd/ip/multi_protocol_bd_axi_vdma_0_0/multi_protocol_bd_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multi_protocol_bd_axi_vdma_0_0 || ORIG_REF_NAME==multi_protocol_bd_axi_vdma_0_0} -quiet] -quiet

# IP: bd/multi_protocol_bd/ip/multi_protocol_bd_v_tc_0_0/multi_protocol_bd_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multi_protocol_bd_v_tc_0_0 || ORIG_REF_NAME==multi_protocol_bd_v_tc_0_0} -quiet] -quiet

# IP: bd/multi_protocol_bd/ip/multi_protocol_bd_v_axi4s_vid_out_0_0/multi_protocol_bd_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multi_protocol_bd_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==multi_protocol_bd_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/multi_protocol_bd_axi_smc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multi_protocol_bd_axi_smc_0_0 || ORIG_REF_NAME==multi_protocol_bd_axi_smc_0_0} -quiet] -quiet

# IP: bd/multi_protocol_bd/ip/multi_protocol_bd_rgb888torgb565_0_0/multi_protocol_bd_rgb888torgb565_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multi_protocol_bd_rgb888torgb565_0_0 || ORIG_REF_NAME==multi_protocol_bd_rgb888torgb565_0_0} -quiet] -quiet

# IP: bd/multi_protocol_bd/ip/multi_protocol_bd_xlconstant_lcd_bl_0/multi_protocol_bd_xlconstant_lcd_bl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multi_protocol_bd_xlconstant_lcd_bl_0 || ORIG_REF_NAME==multi_protocol_bd_xlconstant_lcd_bl_0} -quiet] -quiet

# XDC: bd/multi_protocol_bd/multi_protocol_bd_ooc.xdc
