# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param general.maxThreads 20
set_msg_config -id {HDL-1065} -limit 10000
set_msg_config  -id {Netlist 29-160}  -string {{multi_protocol_bd_processing_system7_0_0.xdc}}  -suppress 
create_project -in_memory -part xc7z020clg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Vivado/Project/Multi_protocol/Multi_protocol.cache/wt [current_project]
set_property parent.project_path D:/Vivado/Project/Multi_protocol/Multi_protocol.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Vivado/Project/Multi_protocol/Multi_protocol.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/hdl/multi_protocol_bd_wrapper.v
add_files D:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/multi_protocol_bd.bd
set_property used_in_implementation false [get_files -all d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_processing_system7_0_0/multi_protocol_bd_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_xbar_0/multi_protocol_bd_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_protocol_converter_0_0/multi_protocol_bd_axi_protocol_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_proc_sys_reset_0_0/multi_protocol_bd_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_proc_sys_reset_0_0/multi_protocol_bd_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_proc_sys_reset_0_0/multi_protocol_bd_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_vdma_0_0/multi_protocol_bd_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_vdma_0_0/multi_protocol_bd_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_vdma_0_0/multi_protocol_bd_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_v_tc_0_0/multi_protocol_bd_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_v_tc_0_0/multi_protocol_bd_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_v_axi4s_vid_out_0_0/multi_protocol_bd_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_v_axi4s_vid_out_0_0/multi_protocol_bd_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_1/bd_7b74_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_1/bd_7b74_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_2/bd_7b74_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_3/bd_7b74_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_4/bd_7b74_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_5/bd_7b74_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_6/bd_7b74_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_10/bd_7b74_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_11/bd_7b74_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_12/bd_7b74_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_13/bd_7b74_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_14/bd_7b74_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_15/bd_7b74_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all D:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/multi_protocol_bd_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Vivado/Project/Multi_protocol/fpga/constraints/ac820_rgbtft.xdc
set_property used_in_implementation false [get_files D:/Vivado/Project/Multi_protocol/fpga/constraints/ac820_rgbtft.xdc]

read_xdc D:/Vivado/Project/Multi_protocol/fpga/constraints/top.xdc
set_property used_in_implementation false [get_files D:/Vivado/Project/Multi_protocol/fpga/constraints/top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top multi_protocol_bd_wrapper -part xc7z020clg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef multi_protocol_bd_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file multi_protocol_bd_wrapper_utilization_synth.rpt -pb multi_protocol_bd_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
