# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/multi_protocol_bd_axi_smc_0_0.xci
# IP: The module: 'multi_protocol_bd_axi_smc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/bd_7b74.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_0/bd_7b74_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_1/bd_7b74_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_2/bd_7b74_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_3/bd_7b74_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_4/bd_7b74_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_5/bd_7b74_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_6/bd_7b74_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_7/bd_7b74_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_8/bd_7b74_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_9/bd_7b74_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_10/bd_7b74_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_11/bd_7b74_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_12/bd_7b74_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_13/bd_7b74_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_14/bd_7b74_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_15/bd_7b74_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_16/bd_7b74_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_1/bd_7b74_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_1/bd_7b74_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_2/bd_7b74_arsw_0_ooc.xdc

# XDC: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_3/bd_7b74_rsw_0_ooc.xdc

# XDC: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_4/bd_7b74_awsw_0_ooc.xdc

# XDC: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_5/bd_7b74_wsw_0_ooc.xdc

# XDC: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_6/bd_7b74_bsw_0_ooc.xdc

# XDC: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_10/bd_7b74_s00a2s_0_ooc.xdc

# XDC: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_11/bd_7b74_sarn_0_ooc.xdc

# XDC: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_12/bd_7b74_srn_0_ooc.xdc

# XDC: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_13/bd_7b74_m00s2a_0_ooc.xdc

# XDC: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_14/bd_7b74_m00arn_0_ooc.xdc

# XDC: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_15/bd_7b74_m00rn_0_ooc.xdc

# XDC: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'multi_protocol_bd_axi_smc_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/multi_protocol_bd_axi_smc_0_0.xci
# IP: The module: 'multi_protocol_bd_axi_smc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/bd_7b74.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_0/bd_7b74_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_1/bd_7b74_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_2/bd_7b74_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_3/bd_7b74_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_4/bd_7b74_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_5/bd_7b74_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_6/bd_7b74_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_7/bd_7b74_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_8/bd_7b74_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_9/bd_7b74_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_10/bd_7b74_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_11/bd_7b74_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_12/bd_7b74_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_13/bd_7b74_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_14/bd_7b74_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_15/bd_7b74_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_16/bd_7b74_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_1/bd_7b74_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_1/bd_7b74_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_2/bd_7b74_arsw_0_ooc.xdc

# XDC: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_3/bd_7b74_rsw_0_ooc.xdc

# XDC: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_4/bd_7b74_awsw_0_ooc.xdc

# XDC: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_5/bd_7b74_wsw_0_ooc.xdc

# XDC: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_6/bd_7b74_bsw_0_ooc.xdc

# XDC: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_10/bd_7b74_s00a2s_0_ooc.xdc

# XDC: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_11/bd_7b74_sarn_0_ooc.xdc

# XDC: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_12/bd_7b74_srn_0_ooc.xdc

# XDC: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_13/bd_7b74_m00s2a_0_ooc.xdc

# XDC: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_14/bd_7b74_m00arn_0_ooc.xdc

# XDC: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/bd_0/ip/ip_15/bd_7b74_m00rn_0_ooc.xdc

# XDC: d:/Vivado/Project/Multi_protocol/Multi_protocol.srcs/sources_1/bd/multi_protocol_bd/ip/multi_protocol_bd_axi_smc_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'multi_protocol_bd_axi_smc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
